
services:
    app:
        build:
            context: .
        container_name: blue_window_test
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: blue_window_test
            MYSQL_ROOT_PASSWORD: root
            #MYSQL_PASSWORD: root
            #MYSQL_USER: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
